var GAME_LEVELS = [
  ["                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",                          
   "                  x        y            y                y                     x",
   "                  x        v            v                v                     x",
   "                  x                                                            x",
   "                  x                                                            x",
   "                  x                         l     ooo         oo               x",
   "                  x                                                   ooo      x",
   "  xxxxxxxxxxxxxxxxx                               xxxx                         x",
   "  x                                          o                        xxx      x",
   "  x                   oo                   xxx                                 x",
   "  x                                  oo                    xxxx                x",
   "  x                                xxxx   x    x                               x",
   "  x                n                      x!!!!x                  o            x",
   "  x  o           xxxxx                    x!!!!x                  xxxx         x",
   "  x              x   x             xx     x!!!!x           n                   x",
   "  x         xxx!!x   x                    x!!!!x                               x",
   "  x   @     x x!!x   x                    x!!!!x                    y          x",
   "  xxxxxxxxxxx xxxx   xxxxx     xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxxxxx",
   "                         x!!!!!x                  x!!!!!x     x!!!x             ",
   "                         x!!!!!x                  x!!!!!x     x!!!x             ",
   "                         x!!!!!x                  x!!!!!x     xxxxx             ",
   "                         xxxxxxx                  xxxxxxx                       ",
   "                                                                                ",
   "                                                                                "],
  ["                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                      x  y     y                                           x                   x",
   "                      x  v     v                     n                     x                   x",
   " xxxxxxxxxxxxxxxxxxxxxx                                                    x                   x",
   " x         y          x                         xxx  xx   x                x                o  x",
   " x         v          x     o    o              x x!!!!!!!x  o             x                   x",
   " x                    x                         x x!!!!!!!x                x               xx  x",
   " x                    x  xxxxxxxxxxx     xxxxxxxx x!!!!!!!x                x   o     xxxx      x",
   " x                                          xxxxx xxxxxxxxxxxxxxxxxxx      x            x      x",
   " x                                              x                   x      xxxxxx       x      x",
   " x               y     xxx                      x                   x                o  x      x",
   " x               v                      xx      x                   x                   x      x",
   " x                         oo                   x                   x        o      xxxxx      x",
   " x                                              x                   x                   x      x",
   " x                                       n      x                   x      xxxx         x      x",
   " x                  o                           x                   x  o      x  oo            x",
   " x                 xxx       xxxxxx    xxxxxxxxxx                   x  o      xyv              x",
   " x                           x    x!!!!x                            x  o      xxxxx            x",
   " x                           x    x!!!!x                            x         x  y         xx  x",
   " x           o           n   x    x!!!!x                            xxxx      x  v             x",
   " x                           x    x!!!!x                            xy=     o x         xxx    x",
   " x        xxxxxxxxxxxxxxxxxxxx    x!!!!x                            x         x       o        x",
   " x        x                       x!!!!x                            x       xxx      xx        x",
   " x        x                       x!!!!x                            x                          x",
   " x   @    x                       x!!!!x                            x                   xxx    x",
   " xxxxxx   x                       x!!!!x                            x                          x",
   " x!!!!!!!!x                       x!!!!x                            x               xxx        x",
   " x!!!!!!!!x                       x!!!!x                            x         xx               x",
   " x!!!!!!!!x                       x!!!!x                            x n                        x",
   " xxxxxxxxxx                       xxxxxx                            xxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                ",
   "                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxxxxxxxxxxxxxxxxxxxx  y  x          y                                            vv          x",
   " x               y       v  x          v                                                 oo     x",
   " x  @            v          x                     o                           oo                x",
   " xxxxx                      x                   xxxx            oo                         xx   x",
   "                      x     x                      x           xxx        xx                    x",
   "               oo   o x     x            o         x                         xxxxxxxxxxxxxxxxxxxxxx",
   "                      x     x          xxxx        x        xxxx   xx                       y   x",
   "!!!!!!xxxxxxxxxxxxxxxxx     x                  n   xy=         x       o                    v   x",
   "!!!!!!x          y          xy=                    x   xxx     x       xx                       x",
   "xxxxxxx          v          x                xxxxxxx        oo x                 o              x",
   "      x                   =yx                x                 x                                x",
   "      x   o         xxxxxxxxx                x            xxxxxx             xxx                x",
   "      x             x                  xxxxxx                           xxx                     x",
   "      xxxx          x          o  xxx     x         xxx               x x        xxxxxxx        x",
   "      x             x                     x      x!!!!!!!!x        x    x    x   x  y         o x",
   "      x     xxxxxxxxx      xxx    xxxx    xxxxxxxx!!!!!!!!xxxxxxx!!!!!!!x           v           x",
   "      x     x                             x      x!!!!!!!!x     x!!!!!!!x                   xxxxx",
   "      x   o x     o     xx                x      xxxxxxxxxx     x!!!!!!!x                       x",
   "      x   xxx                             x                     x!!!!!!!x              xxx      x",
   "      x     x       x     o   o   o       x                     x!!!!!!!x          n            x",
   "      x     x    xx xxxxxxxxxxxxxxxxxxxxxxx                     x!!!!!!!x      xxxxxxxx       s x",
   "      xxx   x                             x                     x!!!!!!!x            y          x",
   "      x     xxx                           x                     xxxxxxxxx       o    v     xxxxxx",
   "      x     x      o                      x                             x      xx          x!!!!x",
   "      x     x                             x                             x                  x!!!!x",
   "      x     xxxxxxxxxxxxxxxxxxxxxxxxxxx   x                             x                   !!!!x",
   "      x       x  vv    vv    vv           x                             xxxxxxxxxx          !!!!x",
   "      xxx     x                           x                                      x          !!!!x",
   "      x                                 o x                                      x          !!!!x",
   "      x    xx                          xxxx                                      x              x",
   "      x!!!!!x       o      o     o        x                                      x     o  o  o  x",
   "      x!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
